# Generated by Django 3.0.2 on 2025-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0002_auto_20200205_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckdmodel',
            name='Blood_Glucose_Random',
        ),
        migrations.RemoveField(
            model_name='ckdmodel',
            name='Blood_Urea',
        ),
        migrations.RemoveField(
            model_name='ckdmodel',
            name='Packed_cell_volume',
        ),
        migrations.RemoveField(
            model_name='ckdmodel',
            name='Serum_Creatine',
        ),
        migrations.RemoveField(
            model_name='ckdmodel',
            name='White_blood_count',
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='Age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='BMI',
            field=models.FloatField(default=22.0),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='BloodPressure',
            field=models.FloatField(default=130),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(default=0.45),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='Glucose',
            field=models.FloatField(default=130),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='Insulin',
            field=models.FloatField(default=85),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='Pregnancies',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='SkinThickness',
            field=models.FloatField(default=20),
        ),
    ]
